# Build settings
gems:
#  - jemoji
  - jekyll-paginate
  - jekyll-email-protect
 
# Site settings
title: "Paulo Gaspar"
description: > # this means to ignore newlines until "email:"
   Tecnologia, Futurismo, Economia, e outros discursos pedantes

email: dont.send@me.emails
#blog logo
logo: "/assets/images/pg_logo.jpg"
# blog cover
cover: "/assets/images/cover3.jpg"

name: 'Paulo Gaspar'
author: 'Paulo Gaspar'
author_image: "/assets/images/author.jpg"

paginate:	5

url: "http://paulogaspar.github.io" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: '@paulomgaspar'

#fill in disqus shortname to use disqus
disqus: paulogaspar

show_drafts: null
lsi: false
incremental: true
permalink: /:title/

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/paulomgaspar
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/paulogaspar
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
